language: node_js
node_js:
  - lts/*
notifications:
  email: false
matrix:
  fast_finish: true
  include:
    - node_js: '4'
    - node_js: '5'
    - node_js: '6'
    - node_js: '7'
    - node_js: '8'
    - node_js: '9'

script: "npm run test"
